#!/usr/bin/env bash

device_name=$1
# remove underscores for device IDs
if [[ "$device_name" == *":"* ]]; then
  # keep device type prefix intact
  device_name="${device_name%:*}:$(echo "${device_name#*:}" | tr '_' ' ')"
else
  device_name="${device_name//_/ }"
fi

status=$2
icon_pack=/usr/local/share/icons/MonoDev
sound_pack=/usr/local/share/sounds/MonoDev
user=$(who | head -n 1 | awk '{print $1}')
uid=$( id -u "$user" )
wal_dir=/home/$user/.cache/wal/colors
icon_color=$(grep -oP '#.*([A-Za-z]|[0-9])' $icon_pack/main_color.svg)

DBUS_SESSION_BUS_ADDRESS=unix:path="/run/user/$uid/bus"
export DBUS_SESSION_BUS_ADDRESS
# required by Libcanberra
XDG_RUNTIME_DIR=/run/user/$uid
export XDG_RUNTIME_DIR
export DISPLAY=:0
export WAYLAND_DISPLAY=wayland-0

notify() {
  if [ "$status" == "add" ]; then
    su "$user" -c "canberra-gtk-play -f ${sound_pack}/add.oga -i 'Devify' -d 'Connected'" 
    su "$user" -c "notify-send -u low -i ${icon_pack}/$2.svg -a Devify '$1' 'Connected'"
  fi

  if [ "$status" == "remove" ]; then
    su "$user" -c "canberra-gtk-play -f ${sound_pack}/remove.oga -i 'Devify' -d 'Disconnected'"
    su "$user" -c "notify-send -u low -i ${icon_pack}/$2.svg -a Devify '$1' 'Disconnected'"
  fi
}

# Change color by pywall

if test -f "$wal_dir"; then
  color=$(sed -n 3p "$wal_dir")
  if [ "$color" != "$icon_color" ]; then
    for i in "$icon_pack"/*; do
      sed -i "s/fill=\"#.*\"/fill=\"$color\"/g" "$i"
    done
  fi
fi

shopt -s nocasematch
case "$device_name" in
  *"DualSense"*)
    notify "PS5 Controller" "ps5_controller"
    ;;
  *"DualShock"*)
    notify "PS4 Controller" "ps4_controller"
    ;;
  *"Pro Controller"*)
    notify "Pro Controller" "switch_pro_controller"
    ;;
  *"Katar"*)
    notify "$device_name" "corsair"
    ;;
  *"Keyboard"*)
    notify "$device_name" "generic_keyboard"
    ;;
  *"Mouse"* | *"Logitech MX"* | *"MX Master"*)
    notify "$device_name" "generic_mouse"
    ;;
  *"X-Box"* | *"Xbox"*)
    notify "Xbox Controller" "xbox_controller"
    ;;
  *"Yubico Yubikey"*)
    notify "Yubikey" "yubikey"
    ;;
  *"Cam"*)
    notify "Webcam" "webcam"
    ;;
  *"usb_drive"*)
    # remove custom prefix set from udev rule
    device_name=${device_name#*:}
    notify "$device_name" "usb_drive"
    ;;
  *"android_device"*)
    # remove custom prefix set from udev rule
    device_name=${device_name#*:}
    notify "$device_name" "android"
    ;;
  *"serial_device"*)
    # remove custom prefix set from udev rule
    device_name=${device_name#*:}
    # special serial device definitions here
    case "$device_name" in
      *"Arduino"*)
        notify "$device_name" "arduino"
        ;;
      *)
        notify "$device_name" "generic_serial"
        ;;
    esac
    ;;
  *)
    notify "$device_name" ""
  ;;
esac
